<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Snake Game</title>
  <style>
    body {
      background-color: #111;
      color: #fff;
      font-family: sans-serif;
      text-align: center;
      margin-top: 20px;
    }
    canvas {
      background: #000;
      display: block;
      margin: 0 auto;
      border: 2px solid #fff;
    }
    h1 {
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
  <h1>🐍 Snake Game</h1>
  <canvas id="game" width="400" height="400"></canvas>
  <script>
    const canvas = document.getElementById("game");
    const ctx = canvas.getContext("2d");

    const box = 20;
    let snake = [{ x: 9 * box, y: 10 * box }];
    let food = {
      x: Math.floor(Math.random() * 19 + 1) * box,
      y: Math.floor(Math.random() * 19 + 1) * box
    };
    let direction = null;
    let score = 0;

    document.addEventListener("keydown", e => {
      if (e.key === "ArrowLeft" && direction !== "RIGHT") direction = "LEFT";
      if (e.key === "ArrowUp" && direction !== "DOWN") direction = "UP";
      if (e.key === "ArrowRight" && direction !== "LEFT") direction = "RIGHT";
      if (e.key === "ArrowDown" && direction !== "UP") direction = "DOWN";
    });

    function draw() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);

      // Draw Snake
      for (let i = 0; i < snake.length; i++) {
        ctx.fillStyle = i === 0 ? "lime" : "green";
        ctx.fillRect(snake[i].x, snake[i].y, box, box);
      }

      // Draw Food
      ctx.fillStyle = "red";
      ctx.fillRect(food.x, food.y, box, box);

      let headX = snake[0].x;
      let headY = snake[0].y;

      // Move direction
      if (direction === "LEFT") headX -= box;
      if (direction === "RIGHT") headX += box;
      if (direction === "UP") headY -= box;
      if (direction === "DOWN") headY += box;

      // Eat food
      if (headX === food.x && headY === food.y) {
        food = {
          x: Math.floor(Math.random() * 19 + 1) * box,
          y: Math.floor(Math.random() * 19 + 1) * box
        };
        score++;
      } else {
        snake.pop();
      }

      const newHead = { x: headX, y: headY };

      // Check collision
      const collision = (
        headX < 0 || headX >= canvas.width ||
        headY < 0 || headY >= canvas.height ||
        snake.some(seg => seg.x === headX && seg.y === headY)
      );

      if (collision) {
        clearInterval(game);
        setTimeout(() => {
          alert("💀 Game Over! Your score: " + score);
          location.reload();
        }, 100);
        return;
      }

      snake.unshift(newHead);
    }

    const game = setInterval(draw, 100);
  </script>
</body>
</html>
